// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // Usando process.env diretamente para permitir fallback durante build
    // O helper env() lança erro se a variável não existe, impedindo o fallback
    url:
      process.env.DATABASE_URL ||
      'postgresql://dummy:dummy@localhost:5432/dummy?schema=public',
  },
});
